### ISSUE TITLE
When will the code come? Thank you!

### ISSUE THREAD

**Issue by wangxiaobaobao** [zuohuif/FairKG4Rec#2]
Hello Zuohui,
I am very interested in your work, and plan to run it on another dataset, could you upload the code?
Thank you very much!
Bests,
Xiuling

**Comment by zuohuif** [comment]
Hello Xiuling,

Thanks for your interests. Due to the Covid-19, it is not easy for us to get access to the machine in the school which I saved the project. Once everything gets back to normal I will organize the code and make it public asap.

Best
Zuohui

**Comment by wangxiaobaobao** [comment]
Sure, Zuohui, thank you very much!
